// src/js/constants/ActionTypes.js
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const GET_CONTACT_LIST = "GET_CONTACT_LIST";
export const GET_CONTACT_LIST_FAILURE = "GET_CONTACT_LIST_FAILURE";
export const GET_CONTACT_LIST_SUCCESS = "GET_CONTACT_LIST_SUCCESS";

export const GET_THREAD_LIST = "GET_THREAD_LIST";
export const GET_THREAD_LIST_FAILURE = "GET_THREAD_LIST_FAILURE";
export const GET_THREAD_LIST_SUCCESS = "GET_THREAD_LIST_SUCCESS";

export const GET_THREAD_MESSAGE_LIST = "GET_THREAD_LIST";
export const GET_THREAD_MESSAGE_LIST_FAILURE = "GET_THREAD_MESSAGE_LIST_FAILURE";
export const GET_THREAD_MESSAGE_LIST_SUCCESS = "GET_THREAD_MESSAGE_LIST_SUCCESS";

export const CREATE_THREAD = "CREATE_THREAD";
export const CREATE_THREAD_FAILURE = "CREATE_THREAD_FAILURE";
export const CREATE_THREAD_SUCCESS = "CREATE_THREAD_SUCCESS";